name: Deploy Documentation 
on:
    push:
        branches: 
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.event.repository.fork == false
        steps:
            - uses: actions/checkout@v3
              with:
                    token: ${{ secrets.PAT }}  # Use your PAT here
            - uses: actions/setup-python@v2
              with:
                    python-version: 3.x
            - run: pip install mkdocs-material
            - run: pip install mkdocs-macros-plugin
            - run: pip install mkdocs-encryptcontent-plugin
            - run: pip install mkdocs-awesome-pages-plugin
            - run: pip install mkdocs-git-revision-date-plugin
            - run: pip install mkdocs-awesome-pages-plugin
            - run: pip install pygments
            - run: pip install pymdown-extensions
            - run: pip install mkdocs-table-reader-plugin   
            - run: mkdocs build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                    github_token: ${{ secrets.PAT }}  # Use your PAT here
                    publish_dir: ./site
env:
    ASIA_191_PASS: ${{secrets.ASIA_191_PASS}}