name: Deploy Documentation 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
       - uses: actions/checkout@v2
       - name: Run the Docker image
         uses: docker://albertkun/mkdocs-teaching-materials
       - run: mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}          
  ASIA_191_PASS: ${{secrets.ASIA_191_PASS}}
