name: Deploy Documentation 
on:
    push:
        branches: 
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.event.repository.fork == false
        container:
            image: albertkun/mkdocs-teaching-material
        steps:
            - uses: actions/checkout@v3
              with:
                    token: ${{ secrets.PAT }}  # Use your PAT here
            - uses: actions/setup-python@v2
              with:
                    python-version: 3.x
            - run: mkdocs build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                    github_token: ${{ secrets.PAT }}  # Use your PAT here
                    publish_dir: ./site
env:
    ASIA_191_PASS: ${{secrets.ASIA_191_PASS}}