name: Deploy Documentation 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
       - uses: actions/checkout@v2
       - name: Deploy
         uses: docker://ghcr.io/peaceiris/mkdocs-material:latest
         with:
           github_token: ${{ secrets.GH_TOKEN }}
           build: 'mkdocs gh-deploy --force'
env:
  ASIA_191_PASS: ${{secrets.ASIA_191_PASS}}